# name: my-actions                 # the name of this work flow
# on: [push]
# jobs:
#   my-helloworld-job:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Say Hello World       
#         run: echo 'Hello World'
#       - name: View a file         
#         run: |
#           echo 'Viewing the file: '
#           cat requirements.txt
    
    
name: Python safety check
on:
  push:
    branches:
      - master

env:
  DEP_PATH: src/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
